export const CHECKLIST_REQUEST = "CHECKLIST_REQUEST";
export const CHECKLIST_SUCCESS = "CHECKLIST_SUCCESS";
export const CHECKLIST_FAIL = "CHECKLIST_FAIL";

export const CHECKLIST_DELETE_REQUEST = "CHECKLIST_DELETE_REQUEST";
export const CHECKLIST_DELETE_SUCCESS = "CHECKLIST_DELETE_SUCCESS";
export const CHECKLIST_DELETE_FAIL = "CHECKLIST_DELETE_FAIL";

export const CHECKLIST_CREATE_REQUEST = "CHECKLIST_CREATE_REQUEST";
export const CHECKLIST_CREATE_SUCCESS = "CHECKLIST_CREATE_SUCCESS";
export const CHECKLIST_CREATE_FAIL = "CHECKLIST_CREATE_FAIL";
export const CHECKLIST_CREATE_RESET = "CHECKLIST_CREATE_RESET";

export const CHECKLIST_UPDATE_REQUEST = "CHECKLIST_UPDATE_REQUEST";
export const CHECKLIST_UPDATE_SUCCESS = "CHECKLIST_UPDATE_SUCCESS";
export const CHECKLIST_UPDATE_FAIL = "CHECKLIST_UPDATE_FAIL";
